// ISO country code for libphonenumber validation (code -> ISO)
export const COUNTRY_CODE_TO_ISO = {
  '+1': 'US',
  '+44': 'GB',
  '+91': 'IN',
  '+61': 'AU',
  '+81': 'JP',
  '+86': 'CN',
  '+49': 'DE',
  '+33': 'FR',
  '+39': 'IT',
  '+34': 'ES',
  '+31': 'NL',
  '+32': 'BE',
  '+41': 'CH',
  '+43': 'AT',
  '+46': 'SE',
  '+47': 'NO',
  '+45': 'DK',
  '+358': 'FI',
  '+353': 'IE',
  '+351': 'PT',
  '+48': 'PL',
  '+7': 'RU',
  '+82': 'KR',
  '+65': 'SG',
  '+60': 'MY',
  '+63': 'PH',
  '+66': 'TH',
  '+84': 'VN',
  '+62': 'ID',
  '+971': 'AE',
  '+966': 'SA',
  '+972': 'IL',
  '+20': 'EG',
  '+27': 'ZA',
  '+234': 'NG',
  '+254': 'KE',
  '+55': 'BR',
  '+52': 'MX',
  '+54': 'AR',
  '+57': 'CO',
  '+58': 'VE',
  '+51': 'PE',
  '+56': 'CL',
  '+593': 'EC',
  '+90': 'TR',
  '+98': 'IR',
  '+92': 'PK',
  '+880': 'BD',
  '+94': 'LK',
  '+977': 'NP',
  '+64': 'NZ',
}

export const COUNTRY_CODES = [
  { code: '+1', country: 'US/Canada' },
  { code: '+44', country: 'UK' },
  { code: '+91', country: 'India' },
  { code: '+61', country: 'Australia' },
  { code: '+81', country: 'Japan' },
  { code: '+86', country: 'China' },
  { code: '+49', country: 'Germany' },
  { code: '+33', country: 'France' },
  { code: '+39', country: 'Italy' },
  { code: '+34', country: 'Spain' },
  { code: '+31', country: 'Netherlands' },
  { code: '+32', country: 'Belgium' },
  { code: '+41', country: 'Switzerland' },
  { code: '+43', country: 'Austria' },
  { code: '+46', country: 'Sweden' },
  { code: '+47', country: 'Norway' },
  { code: '+45', country: 'Denmark' },
  { code: '+358', country: 'Finland' },
  { code: '+353', country: 'Ireland' },
  { code: '+351', country: 'Portugal' },
  { code: '+48', country: 'Poland' },
  { code: '+7', country: 'Russia' },
  { code: '+82', country: 'South Korea' },
  { code: '+65', country: 'Singapore' },
  { code: '+60', country: 'Malaysia' },
  { code: '+63', country: 'Philippines' },
  { code: '+66', country: 'Thailand' },
  { code: '+84', country: 'Vietnam' },
  { code: '+62', country: 'Indonesia' },
  { code: '+971', country: 'UAE' },
  { code: '+966', country: 'Saudi Arabia' },
  { code: '+972', country: 'Israel' },
  { code: '+20', country: 'Egypt' },
  { code: '+27', country: 'South Africa' },
  { code: '+234', country: 'Nigeria' },
  { code: '+254', country: 'Kenya' },
  { code: '+55', country: 'Brazil' },
  { code: '+52', country: 'Mexico' },
  { code: '+54', country: 'Argentina' },
  { code: '+57', country: 'Colombia' },
  { code: '+58', country: 'Venezuela' },
  { code: '+51', country: 'Peru' },
  { code: '+56', country: 'Chile' },
  { code: '+593', country: 'Ecuador' },
  { code: '+90', country: 'Turkey' },
  { code: '+98', country: 'Iran' },
  { code: '+92', country: 'Pakistan' },
  { code: '+880', country: 'Bangladesh' },
  { code: '+94', country: 'Sri Lanka' },
  { code: '+977', country: 'Nepal' },
  { code: '+64', country: 'New Zealand' },
]
